### PR TITLE
Flutter - Bundle a Realm

### PR DESCRIPTION
**Pull request by desistefanova**
Opened because of Community request: [how-can-i-bundle-a-pre-populated-realm-database-in-a-flutter-app](https://www.mongodb.com/community/forums/t/how-can-i-bundle-a-pre-populated-realm-database-in-a-flutter-app/180290)

### CODE REVIEW

**Review by nielsenko — CHANGES_REQUESTED** [review]
I have added my suggestions in PR #17

**Comment by blagoev** [comment]
converted it to draft

**Review by nielsenko — CHANGES_REQUESTED** [review]
Remove the exe files and the web folder 😄

**Review by nielsenko — APPROVED** [review]
LGTM

**Pull request merged**
